spring.application.name=Session6
spring.datasource.url=jdbc:postgresql://localhost:5432/session5
spring.datasource.username=postgres
spring.datasource.password=Huy24092005@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true